import type { MarketSize, TeamStrength } from './entities';

export type TeamConfig = {
  name: string;
  market: MarketSize;
  strength: TeamStrength;
};

export const TEAM_CONFIGS: Record<string, TeamConfig[]> = {
  firstContinent: [
    { name: 'Aurora Sentinels', market: 'large', strength: 'strong' },
    { name: 'Nebula Knights', market: 'huge', strength: 'elite' },
    { name: 'Nova Force', market: 'medium', strength: 'average' },
    { name: 'Pulsar Raiders', market: 'medium', strength: 'strong' },
    { name: 'Quantum Reapers', market: 'small', strength: 'weak' },
    { name: 'Cyber Wolves', market: 'medium', strength: 'average' },
    { name: 'Droid Destroyers', market: 'large', strength: 'strong' },
    { name: 'Ion Storm', market: 'medium', strength: 'average' },
    { name: 'Binary Banshees', market: 'small', strength: 'weak' },
    { name: 'Titan Titans', market: 'huge', strength: 'elite' },
    { name: 'Stellar Spartans', market: 'large', strength: 'strong' },
    { name: 'Vortex Vipers', market: 'medium', strength: 'average' },
    { name: 'Circuit Breakers', market: 'medium', strength: 'average' },
    { name: 'Logic Lords', market: 'small', strength: 'weak' },
    { name: 'Data Dragons', market: 'medium', strength: 'strong' },
    { name: 'Matrix Marauders', market: 'large', strength: 'strong' },
    { name: 'Pixel Pirates', market: 'small', strength: 'average' },
    { name: 'Vector Vanguards', market: 'medium', strength: 'average' },
    { name: 'Render Renegades', market: 'small', strength: 'weak' },
    { name: 'Cache Crusaders', market: 'medium', strength: 'average' },
    { name: 'Stack Stormers', market: 'medium', strength: 'strong' },
    { name: 'Heap Hammers', market: 'small', strength: 'weak' },
    { name: 'Thread Threshers', market: 'medium', strength: 'average' },
    { name: 'Lock Legion', market: 'large', strength: 'strong' },
    { name: 'Async Avengers', market: 'huge', strength: 'elite' },
    { name: 'Sync Saviors', market: 'medium', strength: 'average' },
    { name: 'Null Knights', market: 'small', strength: 'weak' },
    { name: 'Void Wanderers', market: 'small', strength: 'weak' },
    { name: 'Neural Network', market: 'medium', strength: 'strong' },
    { name: 'Algorithm Alliance', market: 'large', strength: 'strong' },
    { name: 'Debug Destroyers', market: 'small', strength: 'average' },
    { name: 'Compile Kings', market: 'medium', strength: 'average' },
    { name: 'Syntax Soldiers', market: 'small', strength: 'weak' },
    { name: 'Protocol Phantoms', market: 'medium', strength: 'strong' },
    { name: 'Gateway Guardians', market: 'large', strength: 'strong' },
    { name: 'Router Raiders', market: 'small', strength: 'average' },
  ],
  
  secondContinent: [
    { name: 'Apex Predators', market: 'huge', strength: 'elite' },
    { name: 'Storm Chasers', market: 'large', strength: 'strong' },
    { name: 'Thunder Bolts', market: 'medium', strength: 'average' },
    { name: 'Lightning Strikes', market: 'medium', strength: 'strong' },
    { name: 'Cyclone Crushers', market: 'large', strength: 'strong' },
    { name: 'Tornado Twisters', market: 'medium', strength: 'average' },
    { name: 'Hurricane Hunters', market: 'medium', strength: 'strong' },
    { name: 'Blizzard Brawlers', market: 'small', strength: 'average' },
    { name: 'Frost Giants', market: 'large', strength: 'strong' },
    { name: 'Ice Dragons', market: 'medium', strength: 'average' },
    { name: 'Glacier Guardians', market: 'small', strength: 'weak' },
    { name: 'Avalanche Riders', market: 'medium', strength: 'average' },
    { name: 'Volcanic Eruption', market: 'huge', strength: 'elite' },
    { name: 'Lava Flow', market: 'medium', strength: 'strong' },
    { name: 'Magma Men', market: 'small', strength: 'average' },
    { name: 'Rock Solid', market: 'medium', strength: 'average' },
    { name: 'Diamond Cutters', market: 'large', strength: 'strong' },
    { name: 'Crystal Shards', market: 'medium', strength: 'average' },
    { name: 'Sapphire Spirits', market: 'medium', strength: 'strong' },
    { name: 'Emerald Empire', market: 'huge', strength: 'elite' },
    { name: 'Ruby Rebels', market: 'medium', strength: 'average' },
    { name: 'Topaz Titans', market: 'small', strength: 'weak' },
    { name: 'Amber Angels', market: 'medium', strength: 'average' },
    { name: 'Onyx Outlaws', market: 'small', strength: 'weak' },
    { name: 'Quartz Quest', market: 'medium', strength: 'strong' },
    { name: 'Jade Juggernauts', market: 'large', strength: 'strong' },
    { name: 'Garnet Gladiators', market: 'medium', strength: 'average' },
    { name: 'Opal Oracle', market: 'small', strength: 'weak' },
    { name: 'Pearl Protectors', market: 'medium', strength: 'average' },
    { name: 'Coral Corsairs', market: 'small', strength: 'weak' },
    { name: 'Jade Jaguars', market: 'medium', strength: 'strong' },
    { name: 'Zephyr Zealots', market: 'small', strength: 'average' },
    { name: 'Tempest Titans', market: 'large', strength: 'strong' },
    { name: 'Monsoon Masters', market: 'medium', strength: 'average' },
    { name: 'Typhoon Troopers', market: 'small', strength: 'weak' },
    { name: 'Gale Gladiators', market: 'medium', strength: 'strong' },
    { name: 'Blaze Bringers', market: 'medium', strength: 'average' },
    { name: 'Inferno Invaders', market: 'large', strength: 'strong' },
    { name: 'Solar Storm', market: 'huge', strength: 'elite' },
    { name: 'Lunar Legion', market: 'medium', strength: 'average' },
  ],
  
  originContinent: [
    { name: 'Metropolis Emperors', market: 'huge', strength: 'elite' },
    { name: 'Imperial Eagles', market: 'huge', strength: 'elite' },
    { name: 'Royal Guards', market: 'large', strength: 'strong' },
    { name: 'Noble Lions', market: 'large', strength: 'strong' },
    { name: 'Crown Jewelers', market: 'medium', strength: 'average' },
    { name: 'Scepter Bearers', market: 'medium', strength: 'strong' },
    { name: 'Throne Defenders', market: 'large', strength: 'strong' },
    { name: 'Palace Protectors', market: 'medium', strength: 'average' },
    { name: 'Dynasty Dragons', market: 'huge', strength: 'elite' },
    { name: 'Empire Enforcers', market: 'large', strength: 'strong' },
    { name: 'Legend Keepers', market: 'medium', strength: 'average' },
    { name: 'Myth Breakers', market: 'small', strength: 'weak' },
    { name: 'Fate Weavers', market: 'medium', strength: 'strong' },
    { name: 'Destiny Chasers', market: 'large', strength: 'strong' },
    { name: 'Fortune Seekers', market: 'medium', strength: 'average' },
    { name: 'Glory Hunters', market: 'small', strength: 'weak' },
    { name: 'Honor Knights', market: 'medium', strength: 'strong' },
    { name: 'Valor Vanguards', market: 'large', strength: 'strong' },
    { name: 'Courage Crusaders', market: 'medium', strength: 'average' },
    { name: 'Wisdom Wizards', market: 'medium', strength: 'average' },
    { name: 'Power Masters', market: 'large', strength: 'strong' },
    { name: 'Authority Lords', market: 'medium', strength: 'strong' },
    { name: 'Command Centurions', market: 'medium', strength: 'average' },
    { name: 'Control Phantoms', market: 'small', strength: 'weak' },
    { name: 'Dominion Demons', market: 'huge', strength: 'elite' },
    { name: 'Supreme Overlords', market: 'large', strength: 'strong' },
    { name: 'Eternal Champions', market: 'medium', strength: 'average' },
    { name: 'Infinite Immortals', market: 'small', strength: 'weak' },
    { name: 'Legacy Lords', market: 'medium', strength: 'strong' },
    { name: 'Heritage Heroes', market: 'large', strength: 'strong' },
    { name: 'Ancestral Avengers', market: 'medium', strength: 'average' },
    { name: 'Dynasty Defenders', market: 'small', strength: 'weak' },
    { name: 'Reign Raiders', market: 'medium', strength: 'strong' },
    { name: 'Sovereign Soldiers', market: 'medium', strength: 'average' },
    { name: 'Majestic Masters', market: 'large', strength: 'strong' },
    { name: 'Regal Raiders', market: 'small', strength: 'average' },
  ],
  
  miningIsland: [
    { name: 'Core Extractors', market: 'large', strength: 'strong' },
    { name: 'Magma Miners', market: 'large', strength: 'strong' },
    { name: 'Crystal Harvesters', market: 'medium', strength: 'average' },
    { name: 'Ore Lords', market: 'medium', strength: 'strong' },
    { name: 'Metal Mongers', market: 'medium', strength: 'average' },
    { name: 'Gem Seekers', market: 'large', strength: 'strong' },
    { name: 'Rock Crushers', market: 'medium', strength: 'average' },
    { name: 'Drill Masters', market: 'medium', strength: 'average' },
    { name: 'Blast Engineers', market: 'small', strength: 'weak' },
    { name: 'Excavation Experts', market: 'medium', strength: 'strong' },
    { name: 'Mining Syndicate', market: 'huge', strength: 'elite' },
    { name: 'Resource Raiders', market: 'medium', strength: 'average' },
    { name: 'Deep Dwellers', market: 'small', strength: 'weak' },
    { name: 'Underground Kings', market: 'large', strength: 'strong' },
    { name: 'Terraform Knights', market: 'medium', strength: 'average' },
    { name: 'Geology Guild', market: 'small', strength: 'weak' },
    { name: 'Mineral Marauders', market: 'medium', strength: 'average' },
    { name: 'Elemental Guardians', market: 'medium', strength: 'strong' },
    { name: 'Earth Shapers', market: 'medium', strength: 'average' },
    { name: 'Stone Wardens', market: 'small', strength: 'weak' },
    { name: 'Iron Forgers', market: 'medium', strength: 'average' },
    { name: 'Steel Smiths', market: 'medium', strength: 'strong' },
    { name: 'Copper Craftsmen', market: 'small', strength: 'weak' },
    { name: 'Bronze Artificers', market: 'small', strength: 'weak' },
    { name: 'Silver Scavengers', market: 'medium', strength: 'average' },
    { name: 'Gold Rushers', market: 'medium', strength: 'average' },
    { name: 'Platinum Prospectors', market: 'small', strength: 'weak' },
    { name: 'Rare Finders', market: 'small', strength: 'weak' },
    { name: 'Cobalt Commanders', market: 'medium', strength: 'strong' },
    { name: 'Titanium Titans', market: 'medium', strength: 'average' },
    { name: 'Nickel Knights', market: 'small', strength: 'weak' },
    { name: 'Zinc Zealots', market: 'small', strength: 'weak' },
    { name: 'Bismuth Battlers', market: 'small', strength: 'weak' },
    { name: 'Tungsten Troopers', market: 'medium', strength: 'average' },
    { name: 'Uranium United', market: 'small', strength: 'weak' },
    { name: 'Lithium Legion', market: 'small', strength: 'weak' },
    { name: 'Carbon Crushers', market: 'medium', strength: 'average' },
    { name: 'Silicon Soldiers', market: 'small', strength: 'weak' },
    { name: 'Osmium Outlaws', market: 'small', strength: 'weak' },
    { name: 'Rhodium Raiders', market: 'small', strength: 'weak' },
    { name: 'Palladium Phantoms', market: 'medium', strength: 'average' },
    { name: 'Indium Invaders', market: 'small', strength: 'weak' },
    { name: 'Gallium Gladiators', market: 'small', strength: 'weak' },
    { name: 'Selenium Storm', market: 'small', strength: 'weak' },
    { name: 'Tellurium Titans', market: 'medium', strength: 'average' },
    { name: 'Antimony Avengers', market: 'small', strength: 'weak' },
    { name: 'Thallium Thunder', market: 'small', strength: 'weak' },
    { name: 'Germanium Giants', market: 'small', strength: 'weak' },
    { name: 'Scandium Spartans', market: 'small', strength: 'weak' },
    { name: 'Vanadium Vipers', market: 'medium', strength: 'average' },
    { name: 'Chromium Chargers', market: 'small', strength: 'weak' },
    { name: 'Manganese Masters', market: 'small', strength: 'weak' },
    { name: 'Cobalt Crushers', market: 'medium', strength: 'average' },
    { name: 'Molybdenum Monarchs', market: 'small', strength: 'weak' },
    { name: 'Ruthenium Raiders', market: 'small', strength: 'weak' },
    { name: 'Cadmium Crusaders', market: 'small', strength: 'weak' },
    { name: 'Hafnium Heroes', market: 'medium', strength: 'average' },
    { name: 'Tantalum Titans', market: 'small', strength: 'weak' },
  ],
};

export function getTeamConfig(region: string, name: string): TeamConfig | undefined {
  const configs = TEAM_CONFIGS[region];
  return configs?.find(c => c.name === name);
}
